version: '3.8'

services:
  rclone_onedrive_edugonmor:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: rclone_onedrive_edugonmor
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CRON_SCHEDULE=${RCLONE_ONEDRIVE_EDUGONMOR_CRON}
      - TZ=${RCLONE_TZ}
      - BACKUP_SOURCE=${RCLONE_ONEDRIVE_EDUGONMOR_SOURCE}
      - BACKUP_DEST=${RCLONE_ONEDRIVE_EDUGONMOR_DEST}
      - RCLONE_CMD=${RCLONE_CMD_SYNC}
      - CHECK_URL=
    volumes:
      - rclone_onedrive_volumen:/data
      - ./config/rclone.conf:/config/rclone.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - shared_network

  rclone_gdrive_udugunmur:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: rclone_gdrive_udugunmur
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CRON_SCHEDULE=${RCLONE_GDRIVE_UDUGUNMUR_CRON}
      - TZ=${RCLONE_TZ}
      - BACKUP_SOURCE=${RCLONE_GDRIVE_UDUGUNMUR_SOURCE}
      - BACKUP_DEST=${RCLONE_GDRIVE_UDUGUNMUR_DEST}
      - RCLONE_CMD=${RCLONE_CMD_SYNC}
      - CHECK_URL=
    volumes:
      - rclone_gdrive_udugunmur_volumen:/data
      - ./config/rclone.conf:/config/rclone.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: shared_network

volumes:
  rclone_onedrive_volumen:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/disk2/rclone/onedrive/edugonmor/sync_edugonmor_backups

  rclone_gdrive_udugunmur_volumen:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/disk2/rclone/gdrive/udugunmur
