version: '3.8'

services:
  edugonmor_cookiecutter_services:
    image: nexus.edugonmor.com/repository/docker-hosted/edugonmor_cookiecutter_services:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edugonmor_cookiecutter_services
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/workspace
    networks:
      - edugonmor_cookiecutter_network
    command: ["tail", "-f", "/dev/null"]

networks:
  edugonmor_cookiecutter_network:
    driver: bridge
