version: '3.8'

services:
  edugonmor_storybook_service:
    image: hello-world
    container_name: edugonmor_storybook_service
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - edugonmor_storybook_network

networks:
  edugonmor_storybook_network:
    driver: bridge
