services:
  {{cookiecutter.project_slug}}_services:
    image: {{cookiecutter.project_slug}}_services:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host # Fix for VPN connection
    container_name: {{cookiecutter.project_slug}}_services
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - {{cookiecutter.project_slug}}_volumen:/var/lib/postgresql/data
      - ./config/init-data.json:/etc/postgresql-custom/init-data.json:ro
    networks:
      - {{cookiecutter._network_name}}
    ports:
      - "${POSTGRES_PORT}:5432"
    command: [
      "postgres",
      "-c",
      "config_file=/etc/postgresql/postgresql.conf"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  {{cookiecutter.project_slug}}_backup:
    image: {{cookiecutter.project_slug}}_backup:latest
    build:
      context: .
      dockerfile: Dockerfile.backup
      network: host
    container_name: {{cookiecutter.project_slug}}_backup
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST={{cookiecutter.project_slug}}_services
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BACKUP_RETENTION=${BACKUP_RETENTION}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - INIT_BACKUP=1
    volumes:
      - {{cookiecutter.project_slug}}_backups:/backups
    networks:
      - {{cookiecutter._network_name}}
    depends_on:
      {{cookiecutter.project_slug}}_services:
        condition: service_healthy

volumes:
  {{cookiecutter.project_slug}}_volumen:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/volumes/{{cookiecutter.project_slug}}_volumen
  {{cookiecutter.project_slug}}_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: {{cookiecutter._rclone_base_path}}/{{cookiecutter.project_slug}}

networks:
  {{cookiecutter._network_name}}:
    external: true
    name: {{cookiecutter._network_name}}
