version: '3.8'

services:
  mysql_services:
    image: mysql_services:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: mysql_services
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volumen:/var/lib/mysql
      - ./config/init-data.json:/etc/mysql/custom/init-data.json:ro
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  mysql_backup:
    image: fradelg/mysql-cron-backup
    container_name: mysql_backup
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql_services
      - MYSQL_USER=root
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=10
      - INIT_BACKUP=1
      - CRON_TIME=0 3 * * *
    volumes:
      - mysql_backups:/backup
    networks:
      - shared_network
    depends_on:
      - mysql_services

networks:
  shared_network:
    external: true
    name: shared_network

volumes:
  mysql_volumen:
  mysql_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/edugonmor/repos/rclone/docker/volumes/rclone_local_backup_volumen/mysql
